### ISSUE TITLE
How to configure the APNS & Cert for Push notification.

### ISSUE THREAD

**Issue by toshanmugaraj** [RocketChat/Docker.Official.Image#118]
When I copy and paste the Key in the PUSH -> APN Cert section, got the below exception. 
`Exception in callback of async function: Error: ENAMETOOLONG: name too long, open 'MIIFgTCCBGmgAwIBAgIIPkUVSEKJB1owDQYJKoZIhvcNAQEFBQAwgZYxCzAJBg 
HwMKS0wrmt3YAv3amyvIrmsN7dKE'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at resolveCredential (/app/bundle/programs/server/npm/node_modules/apn/lib/credentials/resolve.js:16:15)
    at loadCredentials (/app/bundle/programs/server/npm/node_modules/apn/lib/credentials/certificate/load.js:12:16)
    at loadAndValidate (/app/bundle/programs/server/npm/node_modules/apn/lib/credentials/certificate/prepare.js:11:20)
    at config (/app/bundle/programs/server/npm/node_modules/apn/lib/config.js:49:22)
    at new Client (/app/bundle/programs/server/npm/node_modules/apn/lib/client.js:11:19)
    at new Provider (/app/bundle/programs/server/npm/node_modules/apn/lib/provider.js:12:19)
    at initAPN (app/push/server/apn.js:114:18)
    at PushClass.configure (app/push/server/push.js:49:4)
    at configurePush (server/lib/pushConfig.js:109:8)
    at Function.time (/app/bundle/programs/server/profile.js:273:30)
    at /app/bundle/programs/server/boot.js:415:15
    at /app/bundle/programs/server/boot.js:465:7
    at Function.run (/app/bundle/programs/server/profile.js:280:14)
    at /app/bundle/programs/server/boot.js:463:13 {
  errno: -36,`

How to configure the file path of certificate file in Docker.

**Comment by sampaiodiego** [comment]
you don't need to configure the file path, you just need to paste the key content into rocket.chat's settings.

you can take a look into this docs on how to get the appropriate push keys: https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps#push-notification
