### ISSUE TITLE
Can't find migration version 210

### ISSUE THREAD

**Issue by ParkHost** [RocketChat/Docker.Official.Image#126]
after pulling in the new release 3.9.0-rc1 and reverting back to "latest" or earlier i get the following error:
```
Exception in callback of async function: errorClass [Error]: [Can't find migration version 210]
    at Object.Migrations._findIndexByVersion (app/migrations/server/migrations.js:403:8)
    at Object.Migrations._migrateTo (app/migrations/server/migrations.js:254:24)
    at Object.Migrations.migrateTo (app/migrations/server/migrations.js:179:20)
    at module (server/startup/migrations/xrun.js:6:13)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
    at module (server/startup/migrations/index.js:1:4584)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
    at module (server/main.js:1:239)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /app/bundle/programs/server/app/app.js:191694:15
    at /app/bundle/programs/server/boot.js:401:38
    at Array.forEach (<anonymous>)
    at /app/bundle/programs/server/boot.js:226:21
    at /app/bundle/programs/server/boot.js:464:7
    at Function.run (/app/bundle/programs/server/profile.js:280:14)
    at /app/bundle/programs/server/boot.js:463:13 {
  isClientSafe: true,
  error: "Can't find migration version 210",
  reason: undefined,
  details: undefined,
  errorType: 'Meteor.Error'
}
```

i checked in mongodb in the 'migrations' collection:
`{ "_id" : "control", "locked" : true, "version" : 210, "buildAt" : "2020-11-20T02:26:03.782Z", "lockedAt" : ISODate("2020-11-25T20:06:57.100Z") }`

version 210 is defined.. what else is expected to be 210?

**Comment by sampaiodiego** [comment]
unfortunately we don't support rollbacks if there are database migrations in between versions. you can check what the migration 210 does [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/server/startup/migrations/v210.js) and by looking into into I'd say it is safe to unlock manually. to do so, shutdown rocket.chat, go to mongo shell and run the following:
```
db.migrations.update({ _id: 'control' }, { $set: { locked: false, version: 209 } });
```

after that you can spin up "latest" again and you should be fine.
