### ISSUE TITLE
Not start after upgrade to 3.13

### ISSUE THREAD

**Issue by francescodauria** [RocketChat/Docker.Official.Image#139]
I upgraded to version 3.13, but it keeps giving me
SyncedCron ➔ info Finished "Generate download files for user data".

Is there any problem?

**Comment by sampaiodiego** [comment]
how long did you wait? from which version are you coming from? is it consuming CPU or RAM?

**Comment by francescodauria** [comment]
I'm waiting from 2 days, it is RAMconsuming

**Comment by francescodauria** [comment]
I came from version 3.9.1

**Comment by sampaiodiego** [comment]
have you tried troubleshooting it? you can try a few things like:

- stop and start containers
- restart mongodb server
- try using a different (and empty) database (just change the database name on `MONGO_URL` env var)
- increase log level (set the following env var `OVERWRITE_SETTING_Log_Level=2`

I haven't seen other complaints on 3.13 not starting, so I'd try different things not related to rocket.chat itself.

**Comment by francescodauria** [comment]
I managed to get it started, but now I get this message
Exception in callback of async function: errorClass [Error]: [Can't find migration version 220]
I followed this solution https://github.com/RocketChat/Rocket.Chat/issues/11226#issuecomment-399895568
but the db.migrations.find() return me nothing

**Comment by sergeln** [comment]
After upgrading from version 3.13.1 to version 3.13.3, I get the same error.

```
root@jitsimeet:/tmp/bundle/programs/server# systemctl status rocketchat
? rocketchat.service - The Rocket.Chat server
     Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-04-26 17:06:37 +03; 41s ago
   Main PID: 2647 (node)
      Tasks: 11 (limit: 65000)
     Memory: 621.5M
     CGroup: /system.slice/rocketchat.service
             ??2647 /usr/local/bin/node /opt/Rocket.Chat/main.js

Apr 26 17:07:06 jitsimeet rocketchat[2647]:     at /opt/Rocket.Chat/programs/server/boot.js:226:21
Apr 26 17:07:06 jitsimeet rocketchat[2647]:     at /opt/Rocket.Chat/programs/server/boot.js:464:7
Apr 26 17:07:06 jitsimeet rocketchat[2647]:     at Function.run (/opt/Rocket.Chat/programs/server/profile.js:280:14)
Apr 26 17:07:06 jitsimeet rocketchat[2647]:     at /opt/Rocket.Chat/programs/server/boot.js:463:13 {
Apr 26 17:07:06 jitsimeet rocketchat[2647]:   isClientSafe: true,
Apr 26 17:07:06 jitsimeet rocketchat[2647]:   error: "Can't find migration version 220",
Apr 26 17:07:06 jitsimeet rocketchat[2647]:   reason: undefined,
Apr 26 17:07:06 jitsimeet rocketchat[2647]:   details: undefined,
Apr 26 17:07:06 jitsimeet rocketchat[2647]:   errorType
: 'Meteor.Error'
Apr 26 17:07:06 jitsimeet rocketchat[2647]: }
root@jitsimeet:/tmp/bundle/programs/server#
```

Version 220 in the database
```
rs01:PRIMARY> use rocketchat
switched to db rocketchat
rs01:PRIMARY> db.migrations.find()
{ "_id" : "control", "locked" : true, "version" : 220, "buildAt" : "2021-04-20T15:20:09.837Z", "lockedAt" : ISODate("2021-04-26T14:07:06.497Z") }
rs01:PRIMARY>
```
