### ISSUE TITLE
TypeError: AsyncLocalStorage is not a constructor

### ISSUE THREAD

**Issue by col-panic** [RocketChat/Docker.Official.Image#144]
Running this docker image within https://github.com/baloise/rocket-chat-rest-client/blob/master/pom.xml fails with the following error

```
rocketchat> /app/bundle/programs/server/node_modules/fibers/future.js:280
rocketchat> 						throw(ex);
rocketchat> 						^
rocketchat> 
rocketchat> TypeError: AsyncLocalStorage is not a constructor
rocketchat>     at module (server/sdk/index.ts:35:34)
rocketchat>     at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat>     at Module.require (packages/modules-runtime.js:238:14)
rocketchat>     at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
rocketchat>     at ee/server/broker.ts:1:80
rocketchat>     at module (ee/server/broker.ts:361:2)
rocketchat>     at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat>     at Module.require (packages/modules-runtime.js:238:14)
rocketchat>     at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
rocketchat>     at module (server/main.js:1:8)
rocketchat>     at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat>     at Module.require (packages/modules-runtime.js:238:14)
rocketchat>     at require (packages/modules-runtime.js:258:21)
rocketchat>     at /app/bundle/programs/server/app/app.js:202236:15
rocketchat>     at /app/bundle/programs/server/boot.js:401:38
rocketchat>     at Array.forEach (<anonymous>)
rocketchat> Tried 3 times. Waiting 5 secs...
```

**Comment by sampaiodiego** [comment]
it is running version 3.8.3 as per https://github.com/baloise/rocket-chat-rest-client/blob/master/pom.xml#L71 ? if so, and you need to stick to 3.8.x, please try 3.8.8 ..

otherwise I recommend upgrading to latest version, which is 3.15.0

**Comment by col-panic** [comment]
Thanks a lot - both of you mentioned versions seem to do the trick!
