### ISSUE TITLE
rocketchat_1  | Error: a route URL prefix must begin with a slash

### ISSUE THREAD

**Issue by SindenDev** [RocketChat/Docker.Official.Image#164]
rocketchat_1  | /app/bundle/programs/server/node_modules/fibers/future.js:280
rocketchat_1  |                                                 throw(ex);
rocketchat_1  |                                                 ^
rocketchat_1  | 
rocketchat_1  | Error: a route URL prefix must begin with a slash
rocketchat_1  |     at RoutePolicy.declare (packages/routepolicy/routepolicy.js:101:13)
rocketchat_1  |     at new StreamServer (packages/ddp-server/stream_server.js:36:15)
rocketchat_1  |     at new Server (packages/ddp-server/livedata_server.js:1444:24)
rocketchat_1  |     at module (packages/ddp-server/server_convenience.js:6:17)
rocketchat_1  |     at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat_1  |     at Module.require (packages/modules-runtime.js:238:14)
rocketchat_1  |     at require (packages/modules-runtime.js:258:21)
rocketchat_1  |     at /app/bundle/programs/server/packages/ddp-server.js:2353:1
rocketchat_1  |     at /app/bundle/programs/server/packages/ddp-server.js:2360:3
rocketchat_1  |     at /app/bundle/programs/server/boot.js:401:38
rocketchat_1  |     at Array.forEach (<anonymous>)
rocketchat_1  |     at /app/bundle/programs/server/boot.js:226:21
rocketchat_1  |     at /app/bundle/programs/server/boot.js:464:7
rocketchat_1  |     at Function.run (/app/bundle/programs/server/profile.js:280:14)
rocketchat_1  |     at /app/bundle/programs/server/boot.js:463:13
rocketchat_1  | /app/bundle/programs/server/node_modules/fibers/future.js:280
rocketchat_1  |                                                 throw(ex);
rocketchat_1  |                                                 ^
rocketchat_1  | 
rocketchat_1  | Error: a route URL prefix must begin with a slash
rocketchat_1  |     at RoutePolicy.declare (packages/routepolicy/routepolicy.js:101:13)
rocketchat_1  |     at new StreamServer (packages/ddp-server/stream_server.js:36:15)
rocketchat_1  |     at new Server (packages/ddp-server/livedata_server.js:1444:24)
rocketchat_1  |     at module (packages/ddp-server/server_convenience.js:6:17)
rocketchat_1  |     at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat_1  |     at Module.require (packages/modules-runtime.js:238:14)
rocketchat_1  |     at require (packages/modules-runtime.js:258:21)
rocketchat_1  |     at /app/bundle/programs/server/packages/ddp-server.js:2353:1
rocketchat_1  |     at /app/bundle/programs/server/packages/ddp-server.js:2360:3
rocketchat_1  |     at /app/bundle/programs/server/boot.js:401:38
rocketchat_1  |     at Array.forEach (<anonymous>)
rocketchat_1  |     at /app/bundle/programs/server/boot.js:226:21
rocketchat_1  |     at /app/bundle/programs/server/boot.js:464:7
rocketchat_1  |     at Function.run (/app/bundle/programs/server/profile.js:280:14)
rocketchat_1  |     at /app/bundle/programs/server/boot.js:463:13
rocketchat_rocketchat_1 exited with code 1
rocketchat_1  | /app/bundle/programs/server/node_modules/fibers/future.js:280
rocketchat_1  |                                                 throw(ex);
rocketchat_1  |                                                 ^
rocketchat_1  | 
rocketchat_1  | Error: a route URL prefix must begin with a slash
rocketchat_1  |     at RoutePolicy.declare (packages/routepolicy/routepolicy.js:101:13)
rocketchat_1  |     at new StreamServer (packages/ddp-server/stream_server.js:36:15)
rocketchat_1  |     at new Server (packages/ddp-server/livedata_server.js:1444:24)
rocketchat_1  |     at module (packages/ddp-server/server_convenience.js:6:17)
rocketchat_1  |     at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat_1  |     at Module.require (packages/modules-runtime.js:238:14)
rocketchat_1  |     at require (packages/modules-runtime.js:258:21)
rocketchat_1  |     at /app/bundle/programs/server/packages/ddp-server.js:2353:1
rocketchat_1  |     at /app/bundle/programs/server/packages/ddp-server.js:2360:3
rocketchat_1  |     at /app/bundle/programs/server/boot.js:401:38
rocketchat_1  |     at Array.forEach (<anonymous>)
rocketchat_1  |     at /app/bundle/programs/server/boot.js:226:21
rocketchat_1  |     at /app/bundle/programs/server/boot.js:464:7
rocketchat_1  |     at Function.run (/app/bundle/programs/server/profile.js:280:14)
rocketchat_1  |     at /app/bundle/programs/server/boot.js:463:13

**Comment by merlin-tc** [comment]
Your docker version is most likely too old.
Also make sure you use `docker compose up` and not `docker-compose up`.

**Comment by fred-storm** [comment]
Same issue with me on a fresh install.

docker version is 20.10.25
trying chat 6.3.0 with mongo 5.0 and defaults in the .env file other than adding my domain as 'https://cr.domain.net'
<img width="1120" alt="Screen Shot 2023-08-13 at 10 24 08 PM" src="https://github.com/RocketChat/Docker.Official.Image/assets/142193811/492cde08-2108-4314-b461-eeb305b146ce">

**Comment by jaydeep-kuber** [comment]
rocketchat_rocketchat_1 exited with code 1
rocketchat_1  | packages/core-runtime.js:189
rocketchat_1  |             throw error;
rocketchat_1  |             ^
rocketchat_1  | 
rocketchat_1  | Error: a route URL prefix must begin with a slash
rocketchat_1  |     at RoutePolicy.declare (packages/routepolicy/routepolicy.js:101:13)
rocketchat_1  |     at new StreamServer (packages/ddp-server/stream_server.js:38:15)
rocketchat_1  |     at new Server (packages/ddp-server/livedata_server.js:1505:24)
rocketchat_1  |     at module (packages/ddp-server/server_convenience.js:6:17)
rocketchat_1  |     at fileEvaluate (packages/modules-runtime.js:335:7)
rocketchat_1  |     at Module.require (packages/modules-runtime.js:237:14)
rocketchat_1  |     at Module.mod.require (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
rocketchat_1  |     at Object.require (packages/modules-runtime.js:257:21)
rocketchat_1  |     at evaluateNextModule (packages/core-runtime.js:167:26)
rocketchat_1  |     at evaluateNextModule (packages/core-runtime.js:202:7)
rocketchat_1  |     at evaluateNextModule (packages/core-runtime.js:202:7)
rocketchat_1  |     at evaluateNextModule (packages/core-runtime.js:202:7)
rocketchat_1  |     at evaluateNextModule (packages/core-runtime.js:202:7)
rocketchat_1  |     at runEagerModules (packages/core-runtime.js:206:3)
rocketchat_1  |     at processNext (packages/core-runtime.js:128:3)
rocketchat_1  |     at packages/core-runtime.js:138:5
rocketchat_1  | 
rocketchat_1  | Node.js v20.18.0
rocketchat_rocketchat_1 exited with code 1

i'm getting too.
