### ISSUE TITLE
Error on bringing up latest docker compose

### ISSUE THREAD

**Issue by alithechemist** [RocketChat/Docker.Official.Image#198]
Hi, just checked out the git repo, tried to run and got an error on the url of mongodb. Am I Missing something?

```
root@disko:/srv# git clone https://github.com/RocketChat/Docker.Official.Image.git rocketchat
Cloning into 'rocketchat'...
remote: Enumerating objects: 1242, done.
remote: Counting objects: 100% (142/142), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 1242 (delta 118), reused 84 (delta 70), pack-reused 1100
Receiving objects: 100% (1242/1242), 202.85 KiB | 749.00 KiB/s, done.
Resolving deltas: 100% (696/696), done.
root@disko:/srv# cd rocketchat/
root@disko:/srv/rocketchat# docker-compose up
Starting rocketchat_mongodb_1 ... done
Starting rocketchat_rocketchat_1 ... done
Attaching to rocketchat_mongodb_1, rocketchat_rocketchat_1
mongodb_1     | mongodb 08:55:55.69 
mongodb_1     | mongodb 08:55:55.69 Welcome to the Bitnami mongodb container
mongodb_1     | mongodb 08:55:55.69 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb_1     | mongodb 08:55:55.69 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb_1     | mongodb 08:55:55.69 
mongodb_1     | mongodb 08:55:55.70 INFO  ==> ** Starting MongoDB setup **
mongodb_1     | mongodb 08:55:55.71 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb_1     | mongodb 08:55:55.73 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mongodb_1     | mongodb 08:55:55.74 INFO  ==> Initializing MongoDB...
mongodb_1     | mongodb 08:55:55.92 INFO  ==> Deploying MongoDB from scratch...
mongodb_1     | /opt/bitnami/scripts/libos.sh: line 346:    46 Illegal instruction     "$@" > /dev/null 2>&1
rocketchat_1  | /app/bundle/programs/server/node_modules/fibers/future.js:280
rocketchat_1  | 						throw(ex);
rocketchat_1  | 						^
rocketchat_1  | 
rocketchat_1  | MongoRuntimeError: Unable to parse ${MONGODB_ADVERTISED_HOSTNAME:-mongodb:27017 with URL
rocketchat_1  |     at new HostAddress (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:848:34)
rocketchat_1  |     at fromString (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:890:16)
rocketchat_1  |     at Array.map (<anonymous>)
rocketchat_1  |     at parseOptions (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/connection_string.js:197:45)
rocketchat_1  |     at new MongoClient (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:46:63)
rocketchat_1  |     at new MongoConnection (packages/mongo/mongo_driver.js:191:17)
rocketchat_1  |     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:9:16)
rocketchat_1  |     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:66:18)
rocketchat_1  |     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
rocketchat_1  |     at new Collection (packages/mongo/collection.js:127:40)
rocketchat_1  |     at AccountsServer._initializeCollection (packages/accounts-base/accounts_common.js:98:20)
rocketchat_1  |     at new AccountsCommon (packages/accounts-base/accounts_common.js:46:23)
rocketchat_1  |     at new AccountsServer (packages/accounts-base/accounts_server.js:30:5)
rocketchat_1  |     at packages/accounts-base/server_main.js:7:12
rocketchat_1  |     at module (packages/accounts-base/server_main.js:19:31)
rocketchat_1  |     at fileEvaluate (packages/modules-runtime.js:336:7) {
rocketchat_1  |   cause: TypeError [ERR_INVALID_URL] [ERR_INVALID_URL]: Invalid URL: iLoveJS://${MONGODB_ADVERTISED_HOSTNAME:-mongodb:27017
rocketchat_1  |       at new NodeError (internal/errors.js:322:7)
rocketchat_1  |       at onParseError (internal/url.js:270:9)
rocketchat_1  |       at new URL (internal/url.js:346:5)
rocketchat_1  |       at new HostAddress (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:845:19)
rocketchat_1  |       at fromString (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:890:16)
rocketchat_1  |       at Array.map (<anonymous>)
rocketchat_1  |       at parseOptions (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/connection_string.js:197:45)
rocketchat_1  |       at new MongoClient (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:46:63)
rocketchat_1  |       at new MongoConnection (packages/mongo/mongo_driver.js:191:17)
rocketchat_1  |       at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:9:16)
rocketchat_1  |       at Object.<anonymous> (packages/mongo/remote_collection_driver.js:66:18)
rocketchat_1  |       at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
rocketchat_1  |       at new Collection (packages/mongo/collection.js:127:40)
rocketchat_1  |       at AccountsServer._initializeCollection (packages/accounts-base/accounts_common.js:98:20)
rocketchat_1  |       at new AccountsCommon (packages/accounts-base/accounts_common.js:46:23)
rocketchat_1  |       at new AccountsServer (packages/accounts-base/accounts_server.js:30:5) {
rocketchat_1  |     input: 'iLoveJS://${MONGODB_ADVERTISED_HOSTNAME:-mongodb:27017',
rocketchat_1  |     code: 'ERR_INVALID_URL'
rocketchat_1  |   },
rocketchat_1  |   [Symbol(errorLabels)]: Set(0) {}
rocketchat_1  | }
rocketchat_mongodb_1 exited with code 132
```

Thanks in advance

**Comment by alithechemist** [comment]
Actually I'd say it's this: `46 Illegal instruction     "$@" > /dev/null 2>&1` 
I believe that on my system, the defaults values in compose are being somehow messed up...
Am I the only one experiencing this?

**Comment by alithechemist** [comment]
Turns out I was trying to build on an Intel I5 without AVX instruction which is needed by mongodb.

**Comment by WaaromZoMoeilijk** [comment]
Thank you for posting your results, had this same error on a Proxmox VM with processor type "default". Setting it to host fixed it.

**Comment by alithechemist** [comment]
Actually, I assumed my hardware was old, I run it on Proxmox too, but thanks to your comment I changed the cpu type and now it works, thanks!
