### ISSUE TITLE
6.6 docker image creates broken containers (glibcxx_3.4.29)

### ISSUE THREAD

**Issue by AKM-Services** [RocketChat/Docker.Official.Image#207]
Have first tried running the official image rocket.chat:6.6.0. Results in error below.

suspect that the binary node module used was build with a later version of glibc.

(also tried to change the Dockerfile and use bookworm as a base image, but that conks out with a python error)

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /app/bundle/programs/server/npm/node_modules/isolated-vm/out/isolated_vm.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1173:18)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (/app/bundle/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/app/bundle/programs/server/npm/node_modules/isolated-vm/isolated-vm.js:1:-44)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Module.Mp._compile (/app/bundle/programs/server/runtime.js:77:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Module.Mp.load (/app/bundle/programs/server/runtime.js:37:33)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at npmRequire (/app/bundle/programs/server/npm-require.js:111:12)
    at Module.useNode (packages/modules-runtime.js:751:18)
    at module (/app/bundle/programs/server/packages/modules.js:205069:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (app/integrations/server/lib/isolated-vm/isolated-vm.ts:2:43)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (app/integrations/server/lib/triggerHandler.js:1:1149)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at server/services/meteor/service.ts:1:72
    at module (server/services/meteor/service.ts:286:2)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by AKM-Services** [comment]
Seems to be fixed by changing the base image to bookworm-slim and the python install to python3 on line 59

**Comment by C0teDeP0rc** [comment]
Same issue here. I forced the previous version of the container for now.

**Comment by oussjarrousse** [comment]
Same issue here. I faced issues with using an older container, as in my case, upgrading to 6.6 from cause a migration of the DB. I used the following image and it worked for me: docker pull registry.rocket.chat/rocketchat/rocket.chat:latest

**Comment by C0teDeP0rc** [comment]
I tested it with the latest version, but the issue still persists. :(
