### ISSUE TITLE
MongoError: not master and slaveOk=false

### ISSUE THREAD

**Issue by Dremor** [RocketChat/Docker.Official.Image#50]
I'm trying to make RocketChat work with a MongoDB replicaset, but I get the following error: 
```
Exception in callback of async function: MongoError: not master and slaveOk=false

    at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)

    at queryCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:212:36)

    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18

    at _combinedTickCallback (internal/process/next_tick.js:131:7)

    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

Exception in setInterval callback: MongoError: not master

    at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)

    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:497:72

    at authenticateStragglers (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:443:16)

    at Connection.messageHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:477:5)

    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:333:22)

    at emitOne (events.js:116:13)

    at Socket.emit (events.js:211:7)

    at addChunk (_stream_readable.js:263:12)

    at readableAddChunk (_stream_readable.js:250:11)

    at Socket.Readable.push (_stream_readable.js:208:10)

    at TCP.onread (net.js:594:20)
```

Looks like Rocket.Chat don't allow to read from a replica. Would it be possible to change this behaviour?

**Comment by Dremor** [comment]
Bad configuration on my part, sorry.

**Comment by lookatmypinky** [comment]
Any chance you could reveal what the bad configuration happened to be?

**Comment by zolbayars** [comment]
> Bad configuration on my part, sorry.

This exact issue is happening. What was the configuration?

**Comment by mabushey** [comment]
Bad configuration = Braindead idea to use Mongo.

**Comment by sampaiodiego** [comment]
for those who have the same issue, its a MongoDB misconfiguration.. you guys need to configure it in Replica Set mode. There is an official tutorial explaining how to do that: https://docs.mongodb.com/manual/tutorial/deploy-replica-set/

**Comment by Dremor** [comment]
I agree with @sampaiodiego answer, it was a ReplicaSet misconfiguration. I unfortunately don't remember the details, as this notification was buried under all the other ones. I'll try to replicate it if I have the time to do so, but cannot promise.
