### ISSUE TITLE
Exception in callback of async function: Error: [Can't find migration version 143]

### ISSUE THREAD

**Issue by sujaltv** [RocketChat/Docker.Official.Image#78]
Can't find migration version 143

I just pulled a new docker image and I see the age-old recurrent error: Can't find migration version 143; my Mongo version does show it's 143:

```
{ "_id" : "control", "version" : 143, "locked" : true, "lockedAt" : ISODate("2019-05-09T00:29:47.791Z"), "buildAt" : "2018-06-21T18:28:04.858Z" }
```

Here's the log:

```
Exception in callback of async function: Error: [Can't find migration version 143]--
  | at Object.Migrations._findIndexByVersion (/app/bundle/programs/server/packages/rocketchat_migrations.js:405:8)
  | at Object.Migrations._migrateTo (/app/bundle/programs/server/packages/rocketchat_migrations.js:272:22)
  | at Object.Migrations.migrateTo (/app/bundle/programs/server/packages/rocketchat_migrations.js:201:20)
  | at meteorInstall.server.startup.migrations.xrun.js (/app/bundle/programs/server/app/app.js:5229:24)
  | at fileEvaluate (packages/modules-runtime.js:197:9)
  | at require (packages/modules-runtime.js:120:16)
  | at /app/bundle/programs/server/app/app.js:10077:1
  | at /app/bundle/programs/server/boot.js:303:34
  | at Array.forEach (native)
  | at Function._.each._.forEach (/app/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
  | at /app/bundle/programs/server/boot.js:128:5
  | at /app/bundle/programs/server/boot.js:352:5
  | at Function.run (/app/bundle/programs/server/profile.js:510:12)
  | at /app/bundle/programs/server/boot.js:351:11
```

**Comment by sampaiodiego** [comment]
can you please describe exactly what image are you running?

this error will only happen if you have only run any 1.0.x version and then switched back to an older version.

**Comment by sujaltv** [comment]
Docker `rocket.chat:1.0.2`. I never switched back, just fresh instals.

**Comment by sampaiodiego** [comment]
this is weird.. I've checked and `rocket.chat:1.0.2` image definitely have `143` migration.. but it says it was updated 2 days ago, idk what was there before..

can you please pull it again and see if it works? it should work.

**Comment by sujaltv** [comment]
Thanks. That worked.
