### ISSUE TITLE
instructions no longer work due to requirement for OPLOG

### ISSUE THREAD

**Issue by sellersj** [RocketChat/Docker.Official.Image#84]
If you try the instructions on dockerhub, RC won't start up properly
https://hub.docker.com/_/rocket-chat

OPLOG / REPLICASET IS REQUIRED TO RUN ROCKET.CHAT, MORE INFORMATION AT:
https://go.rocket.chat/i/oplog-required

**Comment by medusar** [comment]
Ping...

The same  problem occurred to me

**Comment by jpjohnso** [comment]
This happened to me, too.

**Comment by Neftedollar** [comment]
Same

**Comment by zigitn** [comment]
```
/app/bundle/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^

Error: Error: Unable to find Mongodb Oplog. You must run the server with oplog enabled. Try the following:

                                1. Start your mongodb in a replicaset mode: mongod --smallfiles --oplogSize 128 --replSet rs0

                                2. Start the replicaset via mongodb shell: mongo mongo/meteor --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"

                                3. Start your instance with OPLOG configuration: export MONGO_OPLOG_URL=mongodb://localhost:27017/local MONGO_URL=mongodb://localhost:27017/meteor node main.js

    at BaseDb.handleListener (app/models/server/models/_BaseDb.js:51:11)
    at emitTwo (events.js:126:13)
    at BaseDb.emit (events.js:214:7)
    at _addListener (events.js:249:14)
    at BaseDb.addListener (events.js:297:10)
    at emitter.js (app/authorization/server/publications/permissions/emitter.js:4:13)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at index.js (app/authorization/server/publications/permissions/index.js:1:178)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at index.js (app/authorization/server/index.js:1:1746)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
```

same

**Comment by cinlloc** [comment]
Same problem, does anyone has a workaround?

**Comment by cinlloc** [comment]
For your information, it works doing this: 
```
docker run -d --name db --hostname db mongo:4.0 mongod --smallfiles --oplogSize 128 --replSet rs01
docker run --link db mongo:4.0 mongo db/rocketchat --eval "rs.initiate({ _id: 'rs01', members: [ { _id: 0, host: 'db:27017' } ]})"
docker run -d --link db --env "MONGO_URL=mongodb://db:27017/rocketchat?replicaSet=rs01" --env "MONGO_OPLOG_URL=mongodb://db:27017/local?replicaSet=rs01" rocket.chat```
Haven't found less verbose.

**Comment by crbreingan** [comment]
@cinlloc when you run these commands, does the second image stay running? Or does it stop after a second? On my machine it immediately exits.
